import sys, re
with open(r'c:\work\kenji.blog\content\post\search-algorithms-linear-binary-hash-table-principles\index.md', encoding='utf-8') as f:
    text = f.read()

mapping = {
    'title: "探索アルゴリズム（線形、二分探索とハッシュテーブルの原理）"': 'title: "Search Algorithms (Principles of Linear, Binary Search and Hash Tables)"',
    'description: "データの中から目的の値を見つけ出す探索アルゴリズム。線形探索、二分探索の基礎から、高速な検索を実現するハッシュテーブルの原理まで解説します。"': 'description: "Search algorithms for finding target values within data. Explains the basics of linear search and binary search, up to the principles of hash tables that enable high-speed searching."',
    '# 探索アルゴリズムの基礎と重要性': '# Basics and Importance of Search Algorithms',
    '現代のコンピュータサイエンスにおいて、データの中から目的の値を迅速に見つけ出す **探索アルゴリズム** は、あらゆるソフトウェアやシステムの根幹をなす非常に重要な技術です。データベースの検索、ウェブブラウザでのキーワード検索、スマートフォンの連絡先アプリでの名前の検索など、私たちは日常的に探索アルゴリズムの恩恵を受けています。': 'In modern computer science, **search algorithms**, which quickly find a target value within data, are an extremely important technology that forms the foundation of all software and systems. We benefit from search algorithms daily, such as in database searches, keyword searches in web browsers, and name searches in smartphone contact apps.',
    '本記事では、コンピュータサイエンスの基礎である「線形探索（Linear Search）」と「二分探索（Binary Search）」のアルゴリズムについて、その仕組みや計算量、Pythonによる実装例を交えて詳細に解説します。さらに、これらのアルゴリズムの限界を突破し、圧倒的な検索速度を実現する「ハッシュテーブル（Hash Table）」の原理、ハッシュ関数の役割、そしてハッシュ衝突（Collision）の解決手法に至るまで、深く掘り下げていきます。': 'In this article, we will explain in detail the basics of computer science, "Linear Search" and "Binary Search" algorithms, their mechanisms, time complexities, and implementation examples in Python. Furthermore, we will delve deeply into the principles of the "Hash Table", which breaks through the limits of these algorithms to achieve overwhelming search speeds, the role of hash functions, and methods for resolving hash collisions.',
    '探索アルゴリズムの理解を深めることは、プログラマーとしてのスキルを一段階引き上げるために不可欠です。データ量が少ない場合はアルゴリズムの選択がパフォーマンスに与える影響は微小かもしれませんが、ビッグデータの時代において、数百万、数億というデータの中から瞬時に目的の情報を探し出すためには、適切なアルゴリズムとデータ構造の選択が極めて重要になります。特に、 **時間計算量** ($O(n)$ や $O(\\log n)$、$O(1)$ など) の概念を理解することは、効率的なプログラムを設計する上で欠かせない要素です。': 'Deepening your understanding of search algorithms is essential to elevate your skills as a programmer to the next level. When the amount of data is small, the algorithm choice might have a negligible impact on performance, but in the era of big data, selecting the appropriate algorithm and data structure is extremely important to instantly find target information among millions or billions of pieces of data. In particular, understanding the concept of **time complexity** (such as $O(n)$, $O(\\log n)$, $O(1)$) is an indispensable element in designing efficient programs.',
    '## 1. 線形探索（Linear Search）': '## 1. Linear Search',
    '線形探索は、データ構造（配列やリストなど）の先頭から末尾に向かって、目的の値が見つかるまで順番に一つずつ要素を確認していく、最もシンプルで直感的な探索アルゴリズムです。': 'Linear search is the simplest and most intuitive search algorithm, checking elements one by one in order from the beginning to the end of a data structure (such as an array or list) until the target value is found.',
    '### 1.1 線形探索の仕組み': '### 1.1 Mechanism of Linear Search',
    '線形探索のアルゴリズムは以下の手順で進行します。': 'The linear search algorithm proceeds with the following steps:',
    '1. 配列の最初の要素を取り出します。': '1. Retrieve the first element of the array.',
    '2. 取り出した要素が目的の値（ターゲット）と一致するかどうかを確認します。': '2. Check whether the retrieved element matches the target value.',
    '3. 一致した場合は、その要素のインデックス（位置）を返して探索を終了します。': '3. If it matches, return the index (position) of that element and terminate the search.',
    '4. 一致しなかった場合は、次の要素に進みます。': '4. If it does not match, proceed to the next element.',
    '5. 配列の最後まで確認し、ターゲットが見つからなかった場合は、探索失敗（例えば `-1` や `None` を返す）として終了します。': '5. Check until the end of the array, and if the target is not found, terminate as a search failure (for example, returning `-1` or `None`).',
    'A["探索開始"] --> B["インデックス i = 0"]': 'A["Start search"] --> B["Index i = 0"]',
    'B --> C{"i < 配列の長さ?"}': 'B --> C{"i < length of array?"}',
    'C -- "Yes" --> D{"配列[i] == ターゲット?"}': 'C -->|"Yes"| D{"array[i] == target?"}',
    'C -- "No" --> E["探索失敗（見つからず）"]': 'C -->|"No"| E["Search failed (not found)"]',
    'D -- "Yes" --> F["インデックス i を返す"]': 'D -->|"Yes"| F["Return index i"]',
    'D -- "No" --> G["i を 1 増やす"]': 'D -->|"No"| G["Increment i by 1"]',
    '### 1.2 Pythonによる線形探索の実装': '### 1.2 Python Implementation of Linear Search',
    '以下に、Pythonを用いた線形探索のシンプルな実装例を示します。': 'Below is a simple implementation example of linear search using Python.',
    '線形探索を実行する関数': 'Function to execute linear search',
    ':param arr: 探索対象のリスト': ':param arr: List to be searched',
    ':param target: 見つけ出したい値': ':param target: Value to find',
    ':return: 見つかった場合はそのインデックス、見つからない場合は -1': ':return: Index if found, -1 if not found',
    '# テストデータ': '# Test data',
    'print(f"要素 {target_value} はインデックス {result_index} で見つかりました。")': 'print(f"Element {target_value} was found at index {result_index}.")',
    'print(f"要素 {target_value} はリスト内に存在しません。")': 'print(f"Element {target_value} does not exist in the list.")',
    '線形探索の最大の特徴は、データがソート（整列）されている必要がないという点です。データがバラバラの順序で格納されていても、先頭から順番に確認していくため、確実に目的の値を見つけ出すことができます（または存在しないことを確認できます）。しかし、この「順番にすべてを確認する」という性質が、データ量が多くなった場合のパフォーマンス低下の最大の要因となります。': 'The greatest feature of linear search is that the data does not need to be sorted. Even if the data is stored in random order, because it checks sequentially from the beginning, it can reliably find the target value (or confirm its absence). However, this property of "checking everything in order" becomes the biggest factor in performance degradation when the amount of data is large.',
    '## 2. 二分探索（Binary Search）': '## 2. Binary Search',
    '二分探索は、**あらかじめソート（昇順または降順に整列）されたデータ** に対してのみ適用できる、非常に高速で効率的な探索アルゴリズムです。探索範囲を半分ずつ絞り込んでいくことで、計算量を劇的に削減します。': 'Binary search is an extremely fast and efficient search algorithm that can only be applied to **pre-sorted data (arranged in ascending or descending order)**. It dramatically reduces computational complexity by narrowing the search range in half each time.',
    '### 2.1 二分探索の仕組み': '### 2.1 Mechanism of Binary Search',
    '二分探索は以下の手順で行われます。': 'Binary search is performed with the following steps:',
    '1. 探索対象の配列の「左端（`low`）」と「右端（`high`）」のインデックスを初期化します。': '1. Initialize the indices for the "left end (`low`)" and "right end (`high`)" of the array to be searched.',
    '2. 探索範囲が有効である限り（`low <= high`）、以下の処理を繰り返します。': '2. As long as the search range is valid (`low <= high`), repeat the following process.',
    '3. 探索範囲の中央のインデックス（`mid`）を計算します。': '3. Calculate the central index (`mid`) of the search range.',
    '4. 中央の要素（`arr[mid]`）と目的の値（ターゲット）を比較します。': '4. Compare the central element (`arr[mid]`) with the target value.',
    '5. 一致した場合は、`mid` を返して終了します。': '5. If they match, return `mid` and terminate.',
    '6. 中央の要素がターゲットより小さい場合は、ターゲットは右半分の範囲に存在することになるため、左端を `mid + 1` に更新します。': '6. If the central element is smaller than the target, the target must exist in the right half range, so update the left end to `mid + 1`.',
    '7. 中央の要素がターゲットより大きい場合は、ターゲットは左半分の範囲に存在することになるため、右端を `mid - 1` に更新します。': '7. If the central element is larger than the target, the target must exist in the left half range, so update the right end to `mid - 1`.',
    '8. 探索範囲がなくなっても見つからなかった場合は、探索失敗とします。': '8. If the search range is exhausted and it is not found, treat it as a search failure.',
    'A["探索開始"] --> B["low = 0, high = len - 1"]': 'A["Start search"] --> B["low = 0, high = len - 1"]',
    'B --> C{"low <= high?"}': 'B --> C{"low <= high?"}',
    'C -- "No" --> D["探索失敗"]': 'C -->|"No"| D["Search failed"]',
    'C -- "Yes" --> E["mid = (low + high) / 2"]': 'C -->|"Yes"| E["mid = (low + high) / 2"]',
    'E --> F{"arr[mid] == target?"}': 'E --> F{"arr[mid] == target?"}',
    'F -- "Yes" --> G["mid を返す"]': 'F -->|"Yes"| G["Return mid"]',
    'F -- "No" --> H{"arr[mid] < target?"}': 'F -->|"No"| H{"arr[mid] < target?"}',
    'H -- "Yes" --> I["low = mid + 1"]': 'H -->|"Yes"| I["low = mid + 1"]',
    'H -- "No" --> J["high = mid - 1"]': 'H -->|"No"| J["high = mid - 1"]',
    '### 2.2 Pythonによる二分探索の実装（反復法）': '### 2.2 Python Implementation of Binary Search (Iterative Method)',
    '二分探索（反復法）を実行する関数': 'Function to execute binary search (iterative method)',
    ':param arr: ソート済みの探索対象リスト': ':param arr: Sorted list to be searched',
    '# テストデータ（ソート済みである必要がある）': '# Test data (needs to be sorted)',
    '二分探索の驚異的な性能は、探索範囲を毎回半分に分割するという性質から来ています。例えば、要素数が100万個ある配列に対して線形探索を行うと、最悪の場合100万回の比較が必要になりますが、二分探索を用いれば、わずか20回程度の比較で目的の値を見つけることができます（$2^{20} \\approx 1,000,000$）。このため、大規模なデータセットに対する検索操作において、二分探索は線形探索と比較して圧倒的な優位性を誇ります。数学的には、二分探索の時間計算量は $O(\\log n)$ と表現されます。': 'The astounding performance of binary search comes from its property of dividing the search range in half every time. For example, performing a linear search on an array of 1 million elements requires 1 million comparisons in the worst case, but using binary search allows finding the target value with only about 20 comparisons ($2^{20} \\approx 1,000,000$). Therefore, for search operations on large-scale datasets, binary search boasts an overwhelming superiority over linear search. Mathematically, the time complexity of binary search is expressed as $O(\\log n)$.',
    '## 3. ハッシュテーブル（Hash Table）の原理と構造': '## 3. Principles and Structure of Hash Tables',
    '線形探索の $O(n)$ 、二分探索の $O(\\log n)$ に対して、さらに高速な $O(1)$ （定数時間）での探索を目指すデータ構造が **ハッシュテーブル** （またはハッシュマップ）です。ハッシュテーブルは、「キー（Key）」と「値（Value）」のペアを保存し、キーを用いて値を瞬時に取り出すことができる強力な仕組みです。': 'Aiming for an even faster search in $O(1)$ (constant time) compared to the $O(n)$ of linear search and $O(\\log n)$ of binary search, a **hash table** (or hash map) is the data structure. A hash table is a powerful mechanism that stores "Key" and "Value" pairs and allows instantaneous retrieval of values using the keys.',
    '### 3.1 ハッシュ関数の役割': '### 3.1 The Role of Hash Functions',
    'ハッシュテーブルの中核を担うのが **ハッシュ関数** です。ハッシュ関数は、任意のデータ（キー）を入力として受け取り、固定長の整数値（ハッシュ値）を出力する関数です。このハッシュ値を用いて、データを配列（バケット）のどのインデックスに保存するかを決定します。': 'The **hash function** plays the core role in a hash table. A hash function receives arbitrary data (key) as input and outputs a fixed-length integer value (hash value). Using this hash value, it determines which index in the array (bucket) to store the data.',
    '理想的なハッシュ関数は、以下の条件を満たす必要があります。': 'An ideal hash function needs to satisfy the following conditions:',
    '1. **計算が高速であること** : キーからハッシュ値を求める処理に時間がかかっては、検索全体のパフォーマンスが低下します。': '1. **Fast calculation**: If the process of obtaining a hash value from a key takes time, the overall performance of the search degrades.',
    '2. **決定論的であること** : 同じキーを入力すれば、必ず同じハッシュ値が出力されなければなりません。': '2. **Deterministic**: Inputting the same key must always output the same hash value.',
    '3. **分布が一様であること** : 異なるキーを入力した際に、ハッシュ値が配列の様々なインデックスに均等に分散される（偏りがない）ことが求められます。': '3. **Uniform distribution**: When different keys are input, hash values should be evenly distributed (without bias) across various indices of the array.',
    'A["キー (例: \'Apple\')"] --> B["ハッシュ関数"]': 'A["Key (e.g. \'Apple\')"] --> B["Hash function"]',
    'B --> C["ハッシュ値 (例: 5)"]': 'B --> C["Hash value (e.g. 5)"]',
    'C --> D["配列のインデックス 5 に格納"]': 'C --> D["Store in index 5 of array"]',
    '### 3.2 ハッシュテーブルへのデータの追加と検索': '### 3.2 Adding and Searching Data in Hash Tables',
    'ハッシュテーブルへのデータの追加（Insert）は以下の手順で行われます。': 'Adding (Insert) data to a hash table is performed through the following steps:',
    '1. 追加したいデータのキーをハッシュ関数に渡し、ハッシュ値を計算します。': '1. Pass the key of the data you want to add to the hash function to calculate the hash value.',
    '2. 計算されたハッシュ値を、ハッシュテーブルの配列のサイズで割った余り（モジュロ演算）を求め、実際のインデックスを決定します。': '2. Find the remainder (modulo operation) of the calculated hash value divided by the size of the hash table\'s array to determine the actual index.',
    '3. 決定したインデックスの場所に、キーと値のペアを保存します。': '3. Store the key-value pair at the determined index location.',
    '検索（Search）も同様に、検索したいキーのハッシュ値を計算し、インデックスを求めてその場所のデータを確認するだけです。キーから保存場所が直接計算できるため、データの量に関わらず瞬時に検索が完了します（ $O(1)$ の時間計算量）。': 'Searching (Search) works similarly; you calculate the hash value of the key to search, find the index, and simply check the data at that location. Because the storage location can be calculated directly from the key, the search completes instantly regardless of the amount of data (time complexity of $O(1)$).',
    '### 3.3 ハッシュ衝突（Collision）とその解決法': '### 3.3 Hash Collisions and Their Solutions',
    'ハッシュ関数の出力範囲（配列のサイズ）には限りがあるため、異なるキーから同じハッシュ値（同じインデックス）が生成されてしまうことがあります。これを **ハッシュ衝突（Collision）** と呼びます。ハッシュ衝突は避けられない問題であるため、それを解決するための適切な手法が必要になります。': 'Because the output range of a hash function (array size) is limited, it is possible for different keys to generate the same hash value (the same index). This is called a **hash collision**. Since hash collisions are an unavoidable problem, appropriate methods are required to resolve them.',
    '#### 3.3.1 チェイン法（Separate Chaining）': '#### 3.3.1 Separate Chaining',
    'チェイン法は、配列の各インデックスに「連結リスト（Linked List）」を持たせる手法です。ハッシュ衝突が発生した場合、同じインデックスの連結リストに新しい要素を追加していきます。': 'Separate chaining is a method that gives each index of the array a "Linked List". When a hash collision occurs, new elements are added to the linked list at the same index.',
    '#### 3.3.2 オープンアドレス法（Open Addressing）': '#### 3.3.2 Open Addressing',
    'オープンアドレス法は、追加のデータ構造（連結リストなど）を用いず、ハッシュテーブルの配列自体にすべてのデータを格納する手法です。衝突が発生した場合、あらかじめ決められた規則に従って「空いている別のインデックス（バケット）」を探し、そこにデータを格納します。': 'Open addressing is a method that stores all data within the hash table\'s array itself, without using additional data structures (like linked lists). When a collision occurs, it searches for "another empty index (bucket)" according to a predetermined rule and stores the data there.',
    '代表的な空き場所の探し方（探査手法）には以下のようなものがあります。': 'Typical methods for finding empty locations (probing methods) include the following:',
    '* **線形探査（Linear Probing）** : 衝突が起きたインデックスから順番に（+1, +2, ...）、次の空き場所を探します。': '* **Linear Probing**: Searches for the next empty spot sequentially (+1, +2, ...) starting from the collided index.',
    '* **平方探査（Quadratic Probing）** : 衝突が起きたインデックスから、1の2乗、2の2乗、3の2乗... と間隔を広げながら空き場所を探します。': '* **Quadratic Probing**: Searches for an empty spot by increasing the interval as 1 squared, 2 squared, 3 squared... from the collided index.',
    '* **ダブルハッシュ（Double Hashing）** : 2つ目の異なるハッシュ関数を用いて、次の空き場所を探す間隔を決定します。': '* **Double Hashing**: Determines the interval for finding the next empty spot using a second, different hash function.',
    '### 3.4 Pythonによるハッシュテーブルの実装（チェイン法）': '### 3.4 Python Implementation of Hash Tables (Chaining Method)',
    '以下に、Pythonを用いてチェイン法によるハッシュ衝突解決を備えたシンプルなハッシュテーブルを実装します。': 'Below is a simple hash table implementation equipped with hash collision resolution using the chaining method in Python.',
    'current.value = value  # キーが既に存在する場合は値を更新': 'current.value = value  # Update value if key already exists',
    'return None  # キーが見つからない場合': 'return None  # If key is not found',
    '# ハッシュテーブルのテスト': '# Testing the hash table',
    'print(f"appleの価格: {ht.search(\'apple\')}円")': 'print(f"Price of apple: {ht.search(\'apple\')} yen")',
    'print(f"bananaの価格: {ht.search(\'banana\')}円")': 'print(f"Price of banana: {ht.search(\'banana\')} yen")',
    'print(f"grapeの価格: {ht.search(\'grape\')}円")  # 存在しないキー': 'print(f"Price of grape: {ht.search(\'grape\')} yen")  # Non-existent key',
    'ハッシュテーブルの設計において、ハッシュ関数の品質と配列のサイズ（負荷率：Load Factor）の管理は極めて重要です。データ要素の数が配列のサイズに対して多くなりすぎる（負荷率が高くなる）と、ハッシュ衝突が頻発し、チェイン法では連結リストが長くなり、オープンアドレス法では空き場所を探すための探査回数が増加します。結果として、探索時間が $O(1)$ から $O(n)$ へと劣化してしまいます。これを防ぐために、多くのハッシュテーブルの実装（Pythonの組み込み辞書 `dict` など）では、要素数が増えると自動的に配列のサイズを拡張し、すべての要素のハッシュ値を再計算して配置し直す「リハッシュ（Rehashing）」という処理が行われます。': 'In designing a hash table, managing the quality of the hash function and the size of the array (Load Factor) is extremely important. If the number of data elements becomes too large relative to the array size (the load factor gets high), hash collisions occur frequently; in the chaining method, the linked lists become longer, and in open addressing, the number of probes to find an empty spot increases. As a result, the search time degrades from $O(1)$ to $O(n)$. To prevent this, many hash table implementations (like Python\'s built-in dictionary `dict`) perform a process called "Rehashing", where the array size is automatically expanded and the hash values of all elements are recalculated and repositioned as the number of elements increases.',
    '## 4. アルゴリズムの比較とまとめ': '## 4. Algorithm Comparison and Conclusion',
    'ここまで解説してきた3つの探索アルゴリズム（線形探索、二分探索、ハッシュテーブル）の特性を比較表にまとめます。': 'Let\'s summarize the characteristics of the three search algorithms explained so far (linear search, binary search, hash table) in a comparison table.',
    '| アルゴリズム | 時間計算量 (平均) | 時間計算量 (最悪) | 空間計算量 | 前提条件 | 特徴 |': '| Algorithm | Time Complexity (Average) | Time Complexity (Worst) | Space Complexity | Prerequisites | Characteristics |',
    '| :--- | :---: | :---: | :---: | :--- | :--- |': '| :--- | :---: | :---: | :---: | :--- | :--- |',
    '| **線形探索** | $O(n)$ | $O(n)$ | $O(1)$ | なし | 実装が簡単。小規模データや未ソートデータに適用。 |': '| **Linear Search** | $O(n)$ | $O(n)$ | $O(1)$ | None | Simple implementation. Applicable to small-scale or unsorted data. |',
    '| **二分探索** | $O(\\log n)$ | $O(\\log n)$ | $O(1)$ | ソート済みであること | 高速。配列などランダムアクセス可能なデータ構造が必要。 |': '| **Binary Search** | $O(\\log n)$ | $O(\\log n)$ | $O(1)$ | Must be sorted | Fast. Requires a data structure capable of random access, like an array. |',
    '| **ハッシュテーブル** | $O(1)$ | $O(n)$ | $O(n)$ | ハッシュ関数が必要 | 圧倒的な高速検索が可能だが、メモリを多く消費し、最悪ケースでの性能劣化に注意。 |': '| **Hash Table** | $O(1)$ | $O(n)$ | $O(n)$ | Hash function required | Overwhelmingly fast searches are possible, but it consumes a lot of memory; beware of performance degradation in the worst case. |',
    '状況に応じて適切なアルゴリズムを選択することが、システムのパフォーマンス最適化の鍵となります。メモリに余裕があり、検索速度を最優先する場合はハッシュテーブルが最適です。メモリ制約があり、データが常にソートされた状態を保てるのであれば二分探索が強力な選択肢となります。データ数が非常に少ない場合や、データの追加・削除が頻繁でソートを維持するコストが高い場合は、シンプルな線形探索が結果的に最良の選択となることもあります。': 'Selecting the appropriate algorithm based on the situation is the key to optimizing system performance. If memory is sufficient and search speed is the top priority, a hash table is optimal. If there are memory constraints and the data can always be maintained in a sorted state, binary search becomes a powerful option. When the amount of data is extremely small, or when data additions/deletions are frequent and the cost of maintaining the sorted order is high, the simple linear search may ultimately be the best choice.'
}

out_lines = []
for line in text.splitlines():
    strip_line = line.strip()
    if strip_line in mapping:
        leading_spaces = len(line) - len(line.lstrip())
        out_lines.append((' ' * leading_spaces) + mapping[strip_line])
    else:
        out_lines.append(line)
        
with open(r'c:\work\kenji.blog\content\post\search-algorithms-linear-binary-hash-table-principles\index.en.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(out_lines))
