with open(r'c:\work\kenji.blog\content\post\tree-graph-data-structures-search-dfs-bfs-dijkstra\index.md', 'r', encoding='utf-8') as f:
    text = f.read()

src5 = '## 5. ダイクストラ法（Dijkstra\'s Algorithm）\nダイクストラ法は、重み付きグラフにおいて、ある始点から他のすべての頂点への最短経路を求めるアルゴリズムです。ただし、エッジの重みが非負（0以上）である必要があります。\n\n優先度付きキュー（Priority Queue）を用いることで、効率的に探索を行うことができます。数式表現としては、 $ d(v) $ を始点から頂点 $ v $ までの最短距離とすると、エッジ $ (u, v) $ の重み $ w(u, v) $ に対して、 $ d(v) = \\min(d(v), d(u) + w(u, v)) $ と更新します。数式としては $$ d(v) \\le d(u) + w(u, v) $$ という性質を満たします。ここで、 $ \text{cost} $ が最小となる経路を選びます。\n\n### ダイクストラ法のPython実装例\n\n```python\nimport heapq\n\ndef dijkstra(graph, start):\n    # 最短距離を無限大で初期化\n    distances = {node: float(\'inf\') for node in graph}\n    distances[start] = 0\n    priority_queue = [(0, start)]\n\n    while priority_queue:\n        current_distance, current_node = heapq.heappop(priority_queue)\n\n        if current_distance > distances[current_node]:\n            continue\n\n        for neighbor, weight in graph[current_node].items():\n            distance = current_distance + weight\n            if distance < distances[neighbor]:\n                distances[neighbor] = distance\n                heapq.heappush(priority_queue, (distance, neighbor))\n\n    return distances\n\n# グラフの定義（隣接リスト形式）\ngraph = {\n    \'A\': {\'B\': 5, \'C\': 2},\n    \'B\': {\'D\': 1},\n    \'C\': {\'D\': 8, \'E\': 4},\n    \'D\': {\'E\': 3},\n    \'E\': {}\n}\n\nstart_node = \'A\'\nshortest_paths = dijkstra(graph, start_node)\nprint(f"Shortest paths from {start_node}: {shortest_paths}")\n```'

dst5 = '## 5. Algoritma Dijkstra (Dijkstra\'s Algorithm)\nAlgoritma Dijkstra adalah algoritma untuk mencari jalur terpendek dari suatu titik awal ke semua titik (simpul) lainnya dalam graf berbobot. Namun, bobot dari sisi harus non-negatif (0 atau lebih).\n\nDengan menggunakan antrean prioritas (Priority Queue), penelusuran dapat dilakukan secara efisien. Dalam representasi matematis, jika $ d(v) $ adalah jarak terpendek dari titik awal ke simpul $ v $, maka untuk bobot $ w(u, v) $ dari sisi $ (u, v) $, nilai tersebut diperbarui sebagai $ d(v) = \\min(d(v), d(u) + w(u, v)) $. Secara matematis, hal ini memenuhi properti $$ d(v) \\le d(u) + w(u, v) $$. Di sini, kita memilih jalur dengan $ \\text{biaya} $ terkecil.\n\n### Contoh Implementasi Python dari Algoritma Dijkstra\n\n```python\nimport heapq\n\ndef dijkstra(graph, start):\n    # Menginisialisasi jarak terpendek dengan tak terhingga\n    distances = {node: float(\'inf\') for node in graph}\n    distances[start] = 0\n    priority_queue = [(0, start)]\n\n    while priority_queue:\n        current_distance, current_node = heapq.heappop(priority_queue)\n\n        if current_distance > distances[current_node]:\n            continue\n\n        for neighbor, weight in graph[current_node].items():\n            distance = current_distance + weight\n            if distance < distances[neighbor]:\n                distances[neighbor] = distance\n                heapq.heappush(priority_queue, (distance, neighbor))\n\n    return distances\n\n# Definisi graf (format daftar ketetanggaan)\ngraph = {\n    \'A\': {\'B\': 5, \'C\': 2},\n    \'B\': {\'D\': 1},\n    \'C\': {\'D\': 8, \'E\': 4},\n    \'D\': {\'E\': 3},\n    \'E\': {}\n}\n\nstart_node = \'A\'\nshortest_paths = dijkstra(graph, start_node)\nprint(f"Jalur terpendek dari {start_node}: {shortest_paths}")\n```'

with open(r'c:\work\kenji.blog\content\post\tree-graph-data-structures-search-dfs-bfs-dijkstra\index.id.md', 'r', encoding='utf-8') as f:
    text_id = f.read()

text_id = text_id.replace(src5, dst5)

with open(r'c:\work\kenji.blog\content\post\tree-graph-data-structures-search-dfs-bfs-dijkstra\index.id.md', 'w', encoding='utf-8') as f:
    f.write(text_id)

print("Block 5 replaced!")
